server:
  port: 10601
  servlet:
    context-path: /psyche

spring:
  application:
    #应用名
    name: psyche
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: # ***
    password: # ***
    url:      # ***

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml      #配置mapper路径
