server:
  port: 10601
  servlet:
    context-path: /psyche

spring:
  application:
    #应用名
    name: psyche
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Private10.24
    url: jdbc:mysql://150.158.155.24:3306/genMagic?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT&allowMultiQueries=true


###mybatis配置
#mybatis:
#  mapper-locations: classpath:mapper/*.xml      #配置mapper路径
#  type-aliases-package: com.bikatoo.genmagic.infrastructure.db.model   #配置自动扫描实体类所在包
#  configuration:
#    #驼峰映射
#    map-underscore-to-camel-case: true
##    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml      #配置mapper路径
